<a href="https://colab.research.google.com/github/dajinkya1099/AI_ML_Training/blob/main/AjinkyaDhumal_assignment1/numpy_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1 Import NumPy and print its version.
import numpy as np


print(np.__version__)

2.1.3


In [ ]:
from google.colab import files

uploaded = files.upload()

In [5]:
# 2 Make an array from the hours logged column.


import pandas as pd
df = pd.read_csv('it_services_tickets_raw.csv')
hours = df["hours_logged"].to_numpy()
print(hours)

['?' '1.34 ' '7' ... '5' '2' '6.5 hrs']


In [6]:
#3 Print the shape, the size and the data type of that array.
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Dtype:", hours.dtype)

Shape: (49588,)
Size: 49588
Dtype: object


In [7]:
#4 Make an array of the numbers 1 to 50 using arange.
arr = np.arange(1, 51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [8]:
#5 Make 10 evenly spaced numbers between 0 and 100 using linspace.
print(np.linspace(0, 100, 10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [9]:
#6 Make an array of 10 zeros and an array of 10 ones.
print("Array with 10 zeros: ",np.zeros(10))
print("Array with 10 ones: " ,np.ones(10))

Array with 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array with 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#7 Make a 3 by 3 array of random numbers using seed 42.
np.random.seed(42)
print(np.random.rand(3, 3))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [11]:
# 8 Make a 2-D array from the hours logged and billing rate columns.
twoDimArray = df[["hours_logged", "Billing Rate (USD)"]].to_numpy()
print(twoDimArray)

[['?' '$39.45']
 ['1.34 ' '33.15']
 ['7' '48.10']
 ...
 ['5' '24.94']
 ['2' '$116.76']
 ['6.5 hrs' ' 89.02 ']]


In [12]:
# 9 Print how many dimensions that 2-D array has.
print(twoDimArray.ndim)
print(hours.ndim)

2
1


In [13]:
# 10 Print the first 5 values of the hours array.
print(hours[:5])

['?' '1.34 ' '7' '34.630' '12.76 ']


In [14]:
# 11 Print the last 5 values of the hours array.
print(hours[-5:])

['4' '47' '5' '2' '6.5 hrs']


In [15]:
# 12 Print every second value from the first 20 values.
print(hours[:20:2])

['?' '7' '12.76 ' '--' '1.660' nan '11.63' '28' '0.59' '253.85']


In [16]:
# 13 Reverse the array.
print(hours[::-1])

['6.5 hrs' '2' '5' ... '7' '1.34 ' '?']


In [19]:
# 14 Find the sum of the hours array.
hours = pd.to_numeric(df["hours_logged"], errors="coerce")

print(np.sum(hours))

2376713.1


In [23]:
# 15 Find the mean, the minimum and the maximum of the hours array.

df["hours_logged"] = pd.to_numeric(
    df["hours_logged"].astype(str).str.strip(),
    errors="coerce"
)


hours = np.array(df["hours_logged"].dropna(), dtype=float)


print("Mean:", np.mean(hours))
print("Min:", np.min(hours))
print("Max:", np.max(hours))

Mean: 63.614814913947704
Min: -12.5
Max: 9888.01


In [25]:
# 16 Find the standard deviation.
print(np.std(hours))

497.7190812291573


In [26]:
# 17 Find the median.
hours = pd.to_numeric(pd.Series(hours), errors="coerce").to_numpy()
print(np.nanmedian(hours))

13.13


In [28]:
# 18 Count how many values are missing in the array.
print(np.isnan(hours).sum())

0


In [29]:
# 19 Find the mean while ignoring the missing values.
print(np.nanmean(hours))

63.614814913947704


In [30]:
# 20 Replace all the missing values with 0.
hours_filled = np.nan_to_num(hours, nan=0.0)
print(hours_filled)

[ 1.34  7.   34.63 ... 47.    5.    2.  ]


In [31]:
# 21 Count how many values are greater than 100.
print((hours > 100).sum())

1633


In [32]:
# 22 Show only the values that are greater than 100.
print(hours[hours > 100])

[ 253.85  128.   1900.66 ...  562.22  141.9   137.56]


In [33]:
# 23 Show the values that are between 10 and 50.
print(hours[(hours > 10) & (hours < 50)])

[34.63 12.76 15.3  ... 19.   25.23 47.  ]


In [34]:
# 24 Count how many values are negative.
print((hours<0).sum())

140


In [35]:
# 25 Replace all the negative values with 0.
hours[hours<0]=0
print(hours)

[ 1.34  7.   34.63 ... 47.    5.    2.  ]


In [36]:
# 26 Sort the array from smallest to largest.
print(np.sort(hours))

[   0.      0.      0.   ... 8760.   9888.01 9888.01]


In [37]:
# 27 Find the position of the largest value.
print(np.nanargmax(hours))

7590


In [41]:
# 28 Find the position of the smallest value.
print(np.nanargmin(hours))


61


In [42]:
# 29 Find the 5 largest values.
np.sort(hours[~np.isnan(hours)])[::-1][:5]

array([9888.01, 9888.01, 8760.  , 8760.  , 8760.  ])

In [43]:
# 30 Round every value to 1 decimal place.
print(np.round(hours,1))

[ 1.3  7.  34.6 ... 47.   5.   2. ]


In [44]:
# 31 Multiply every value by 2.
print(hours*2)

[ 2.68 14.   69.26 ... 94.   10.    4.  ]


In [45]:
# 32 Add 10 to every value.
print(hours+10)

[11.34 17.   44.63 ... 57.   15.   12.  ]


In [50]:
# 33 Multiply the hours array by the billing rate array.


df["hours_logged"] = pd.to_numeric(df["hours_logged"], errors="coerce")


df["Billing Rate (USD)"] = pd.to_numeric(
    df["Billing Rate (USD)"].astype(str)
    .str.replace(r"[$,]|USD", "", regex=True)
    .str.strip(),
    errors="coerce"
)


valid = df[["hours_logged", "Billing Rate (USD)"]].dropna()


hours = valid["hours_logged"].to_numpy()
rates = valid["Billing Rate (USD)"].to_numpy()


print(hours * rates)

[  44.421   336.7    1834.6974 ... 1071.6     124.7     233.52  ]


In [51]:
# 34 Check whether the two arrays have the same length.
print(len(hours) == len(rates))
print(hours.shape == rates.shape)

True
True


In [52]:
# 35 Use np.where to mark values above 24 as slow and the rest as fast.
speed = np.where(hours >24, "slow","fast")
print(speed)

['fast' 'fast' 'slow' ... 'slow' 'fast' 'fast']


In [53]:
# 36 Make an array of the unique priority values.
priority = df["PRIORITY"].fillna("Unknown").to_numpy()
print(np.unique(priority))

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4']


In [54]:
# 37 Count how many times each unique priority value appears
values, counts = np.unique(priority, return_counts=True)
print(values, counts)

[' ' '-' '--' '1' '2' '3' '4' '?' 'CRITICAL' 'Critical' 'HIGH' 'High'
 'LOW' 'Low' 'MEDIUM' 'Medium' 'P1' 'P1 - Critical' 'P2' 'P3' 'P4'
 'PRIORITY' 'Unknown' 'high' 'low' 'medium' 'missing' 'na' 'p1' 'p2' 'p3'
 'p4'] [  97  108  111 1992 2019 1995 1968   90 2047 2063 2005 2059 2002 1900
 2013 2015 1945 2044 1967 2010 1930    4  856 2029 2003 2072  128  132
 1993 1961 2069 1961]


In [55]:
# 38 Take the first 100 values and reshape them into a 10 by 10 array.
grid = hours[:100].reshape(10, 10)
print(grid.shape)

(10, 10)


In [56]:
# 39 Transpose that 10 by 10 array.
print(grid.T)

[[ 1.34000e+00  2.80000e+01  6.91000e+00  3.92000e+00  1.40000e+01
   1.33350e+02  1.91700e+01  8.00000e+00  3.05500e+01  5.98000e+01]
 [ 7.00000e+00  1.01600e+01  3.08400e+01  2.02200e+01  5.00000e+00
   4.00000e+00  1.78600e+01  3.81000e+00  9.72000e+00  3.55400e+01]
 [ 3.46300e+01  5.90000e-01  3.51000e+00  2.41500e+01  1.14100e+01
   2.00000e+00  9.21000e+00  3.73680e+02  2.35400e+01  3.81900e+01]
 [ 1.27600e+01  7.00000e+00  1.80000e+01  8.40000e+01  1.80000e+01
   2.05100e+01  5.40000e+01  1.13800e+01  9.30000e+00  5.02000e+00]
 [ 1.53000e+01  2.53850e+02  3.14400e+01  2.70000e+01  1.28000e+02
   1.13300e+01  2.00000e+01  3.36700e+01  3.33700e+01  2.70400e+01]
 [ 9.00000e+00  4.20000e+00  3.42000e+00  4.00000e+00  1.54000e+01
   5.99100e+01  6.00000e+00  5.80000e-01  9.32000e+00  1.67600e+01]
 [ 1.66000e+00  5.08100e+01  2.44600e+01  2.76000e+00  1.90066e+03
   2.29700e+01  1.15600e+01  7.00000e+00  4.40000e+00  7.32000e+00]
 [ 1.44000e+00  8.01000e+00  1.15100e+01  1.12600e+01  

In [57]:
# 40 Flatten it back into a 1-D array.
print(grid.flatten())

[ 1.34000e+00  7.00000e+00  3.46300e+01  1.27600e+01  1.53000e+01
  9.00000e+00  1.66000e+00  1.44000e+00  1.16300e+01  7.23100e+01
  2.80000e+01  1.01600e+01  5.90000e-01  7.00000e+00  2.53850e+02
  4.20000e+00  5.08100e+01  8.01000e+00  6.79400e+01  3.27100e+01
  6.91000e+00  3.08400e+01  3.51000e+00  1.80000e+01  3.14400e+01
  3.42000e+00  2.44600e+01  1.15100e+01  6.30200e+01  1.03000e+00
  3.92000e+00  2.02200e+01  2.41500e+01  8.40000e+01  2.70000e+01
  4.00000e+00  2.76000e+00  1.12600e+01  2.40000e+01  5.26000e+00
  1.40000e+01  5.00000e+00  1.14100e+01  1.80000e+01  1.28000e+02
  1.54000e+01  1.90066e+03  4.00000e+00  3.00000e+00  9.00000e+00
  1.33350e+02  4.00000e+00  2.00000e+00  2.05100e+01  1.13300e+01
  5.99100e+01  2.29700e+01 -1.20000e+01  3.40000e+01  1.49200e+01
  1.91700e+01  1.78600e+01  9.21000e+00  5.40000e+01  2.00000e+01
  6.00000e+00  1.15600e+01  5.85000e+00  1.30000e+01  1.09100e+01
  8.00000e+00  3.81000e+00  3.73680e+02  1.13800e+01  3.36700e+01
  5.80000e

In [58]:
# 41 Join two arrays together using np.concatenate.
combinedArray = np.concatenate([hours, rates])
print(combinedArray.shape)

(70958,)


In [59]:
# 42 Split an array into 5 equal parts.
parts = np.array_split(hours, 5)
for i, p in enumerate(parts):
    print(i, p.shape)

0 (7096,)
1 (7096,)
2 (7096,)
3 (7096,)
4 (7095,)


In [60]:
# 43 Find the 25th, 50th and 75th percentile.
print(np.nanpercentile(hours, [25, 50, 75]))

[ 4.34 13.1  29.4 ]


In [61]:
# 44 Find the cumulative sum of the first 20 values.
print(np.cumsum(hours[:20]))

[  1.34   8.34  42.97  55.73  71.03  80.03  81.69  83.13  94.76 167.07
 195.07 205.23 205.82 212.82 466.67 470.87 521.68 529.69 597.63 630.34]


In [62]:
# 45 Find the difference between each value and the one before it using np.diff.
print(np.diff(hours))

[  5.66  27.63 -21.87 ...  43.   -42.    -3.  ]


In [63]:
# 46 Keep every value inside the range 0 to 100 using np.clip.
print(np.clip(hours, 0, 100))

[ 1.34  7.   34.63 ... 47.    5.    2.  ]


In [64]:
# 47 Convert the array to whole numbers.
hours_int = np.nan_to_num(hours).astype(int)
print(hours_int)

[ 1  7 34 ... 47  5  2]


In [65]:
# 48 Copy the array, change one value in the copy, and show that the original did not change.
hours_copy = hours.copy()
hours_copy[0] = 999
print("Copy array: ", hours_copy[0])
print("Original array: ", hours[0])

Copy array:  999.0
Original array:  1.34


In [68]:
# 49 Save the array to a .npy file and load it back.
np.save("hours.npy", hours)

hours_loaded = np.load("hours.npy")

print("Loaded array:", hours_loaded)


Loaded array: [ 1.34  7.   34.63 ... 47.    5.    2.  ]


In [67]:
# 50 Find the total revenue using np.dot on the hours array and the rate array.
total_revenue = np.dot(hours, rates)

print("Total Revenue:", total_revenue)

Total Revenue: 181194844.63470006
